# Time limit to pass to solver (in minutes, zero for no limit)
time_limit_in_mins = 60

# Additive approximation target (0 == no limit)
absolute_gap_limit = 5

# Probability to initialize variable at previously found solution
warm_start_prob = 0.5

# Whether to log solution stats to sheet
log_stats = true

# Whether to log duplicating (and possibly overriding) constraints
log_duplicates = false