# Time limit to pass to solver (in minutes, zero for no limit)
time_limit_in_mins = 30

# Additive approximation target (0 == exact)
absolute_gap_limit = 0

# Probability to initialize each assignment at previously found solution 
# (0 == disable warm start)
warm_start_prob = 0.0

# Whether to log solution stats to sheet
log_stats = true

# Whether to log duplicating (and possibly overriding) constraints
log_duplicates = false