# Time limit to pass to solver (in minutes, zero for no limit)
time_limit = 5

# Whether to initialize at previously found solution
warmstart = false

# Whether to dump solution stats to sheet
stats = true